[env]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 115200
lib_deps =
  sandeepmistry/LoRa
  adafruit/Adafruit BMP280 Library
  adafruit/Adafruit Unified Sensor
  adafruit/DHT sensor library

[env:gateway]
extends = env
build_src_filter =
  +<gateway.cpp>

[env:sender]
extends = env
build_src_filter =
  +<sender.cpp>
